### ISSUE TITLE
[overall] PLD versionning

### ISSUE THREAD

**Issue by kevinpolossat** [ToFeet/tofeet#27]

**Comment by fraiss-c** [comment]
Regarding the PLD's content (almost tables) I think asciidoc isn't the most adapted language in order to do this document, any other suggestions ?

**Comment by polosskevin** [comment]
You can do table in ascii doc

**Comment by polosskevin** [comment]
how is it going ?

**Comment by polosskevin** [comment]
follow up is in a bit more than 10 days, it is a number one priority.
